import { Hono } from "hono";
import { userRouter } from "./user/router";
import { adminRouter } from "./admin/router";
import { organizationRouter } from "./organization/router";
import { matchRouter } from "./match/router";
import { matchIntentRouter } from "./match_intents/router";
import { notificationRouter } from "./notification/router";
import { levelRouter } from "./level/router";
import { challengeRouter } from "./challenge/router";
import { streakRouter } from "./streak/router";
import { rewardRouter } from "./reward/router";
import { leaderboardRouter } from "./leaderboard/router";
import { cronRouter } from "./cron/router";
import { uploadRouter } from "./upload/router";
import { conversationRouter } from "./conversation/router";
import { eventRouter } from "./event/router";
import { accountDeletionRequestRouter } from "./account-deletion-request/router";
import { courtRouter } from "./court/router";
import { clubMemberRouter } from "./club-member/router";

export const serverRouter = new Hono();

serverRouter.route("/user", userRouter);
serverRouter.route("/admin", adminRouter);
serverRouter.route("/organization", organizationRouter);
serverRouter.route("/match", matchRouter);
serverRouter.route("/match-intents", matchIntentRouter);
serverRouter.route("/notification", notificationRouter);
serverRouter.route("/level", levelRouter);
serverRouter.route("/challenge", challengeRouter);
serverRouter.route("/streak", streakRouter);
serverRouter.route("/reward", rewardRouter);
serverRouter.route("/leaderboard", leaderboardRouter);
serverRouter.route("/cron", cronRouter);
serverRouter.route("/upload", uploadRouter);
serverRouter.route("/conversation", conversationRouter);
serverRouter.route("/event", eventRouter);
serverRouter.route("/account-deletion-request", accountDeletionRequestRouter);
serverRouter.route("/court", courtRouter);
serverRouter.route("/club-member", clubMemberRouter);
