import "dotenv/config";
import { db } from "../db";
import { challengeTemplate } from "../db/schema/challenge/schema";

const CHALLENGE_TEMPLATES = [
  // ============================================
  // QUANTITATIVE - Nombre de matchs joués
  // ============================================
  {
    code: "play_1_match",
    type: "quantitative" as const,
    difficulty: "easy" as const,
    titleFr: "Premier pas",
    titleEn: "First Step",
    descriptionFr: "Joue 1 match cette semaine",
    descriptionEn: "Play 1 match this week",
    targetValue: 1,
    acesReward: 50,
    minLevel: 1,
    maxLevel: 5,
  },
  {
    code: "play_3_matches",
    type: "quantitative" as const,
    difficulty: "easy" as const,
    titleFr: "Échauffement",
    titleEn: "Warm Up",
    descriptionFr: "Joue 3 matchs cette semaine",
    descriptionEn: "Play 3 matches this week",
    targetValue: 3,
    acesReward: 100,
    minLevel: 1,
    maxLevel: null,
  },
  {
    code: "play_5_matches",
    type: "quantitative" as const,
    difficulty: "medium" as const,
    titleFr: "Entraînement intensif",
    titleEn: "Intense Training",
    descriptionFr: "Joue 5 matchs cette semaine",
    descriptionEn: "Play 5 matches this week",
    targetValue: 5,
    acesReward: 200,
    minLevel: 3,
    maxLevel: null,
  },
  {
    code: "play_7_matches",
    type: "quantitative" as const,
    difficulty: "hard" as const,
    titleFr: "Machine de guerre",
    titleEn: "War Machine",
    descriptionFr: "Joue 7 matchs cette semaine",
    descriptionEn: "Play 7 matches this week",
    targetValue: 7,
    acesReward: 350,
    minLevel: 5,
    maxLevel: null,
  },
  {
    code: "play_10_matches",
    type: "quantitative" as const,
    difficulty: "hard" as const,
    titleFr: "Marathonien",
    titleEn: "Marathon Runner",
    descriptionFr: "Joue 10 matchs cette semaine",
    descriptionEn: "Play 10 matches this week",
    targetValue: 10,
    acesReward: 500,
    minLevel: 10,
    maxLevel: null,
  },
  // Jouer plusieurs jours différents
  {
    code: "play_3_different_days",
    type: "quantitative" as const,
    difficulty: "easy" as const,
    titleFr: "Régularité",
    titleEn: "Consistency",
    descriptionFr: "Joue au moins 1 match sur 3 jours différents",
    descriptionEn: "Play at least 1 match on 3 different days",
    targetValue: 3,
    acesReward: 125,
    minLevel: 2,
    maxLevel: null,
  },
  {
    code: "play_5_different_days",
    type: "quantitative" as const,
    difficulty: "medium" as const,
    titleFr: "Assidu",
    titleEn: "Dedicated",
    descriptionFr: "Joue au moins 1 match sur 5 jours différents",
    descriptionEn: "Play at least 1 match on 5 different days",
    targetValue: 5,
    acesReward: 250,
    minLevel: 5,
    maxLevel: null,
  },
  {
    code: "play_every_day",
    type: "quantitative" as const,
    difficulty: "hard" as const,
    titleFr: "Aucun répit",
    titleEn: "No Rest",
    descriptionFr: "Joue au moins 1 match chaque jour de la semaine",
    descriptionEn: "Play at least 1 match every day of the week",
    targetValue: 7,
    acesReward: 450,
    minLevel: 10,
    maxLevel: null,
  },
  // Weekend warrior
  {
    code: "weekend_warrior",
    type: "quantitative" as const,
    difficulty: "easy" as const,
    titleFr: "Guerrier du weekend",
    titleEn: "Weekend Warrior",
    descriptionFr: "Joue 2 matchs pendant le weekend",
    descriptionEn: "Play 2 matches during the weekend",
    targetValue: 2,
    acesReward: 100,
    minLevel: 1,
    maxLevel: null,
  },
  {
    code: "weekend_champion",
    type: "quantitative" as const,
    difficulty: "medium" as const,
    titleFr: "Champion du weekend",
    titleEn: "Weekend Champion",
    descriptionFr: "Joue 4 matchs pendant le weekend",
    descriptionEn: "Play 4 matches during the weekend",
    targetValue: 4,
    acesReward: 225,
    minLevel: 5,
    maxLevel: null,
  },

  // ============================================
  // SOCIAL - Interactions avec d'autres joueurs
  // ============================================
  {
    code: "play_with_new_player",
    type: "social" as const,
    difficulty: "easy" as const,
    titleFr: "Nouvelle rencontre",
    titleEn: "New Encounter",
    descriptionFr: "Joue avec un joueur que tu n'as jamais affronté",
    descriptionEn: "Play with a player you've never faced before",
    targetValue: 1,
    acesReward: 75,
    minLevel: 1,
    maxLevel: null,
  },
  {
    code: "play_with_3_different_players",
    type: "social" as const,
    difficulty: "medium" as const,
    titleFr: "Explorateur",
    titleEn: "Explorer",
    descriptionFr: "Joue avec 3 joueurs différents cette semaine",
    descriptionEn: "Play with 3 different players this week",
    targetValue: 3,
    acesReward: 150,
    minLevel: 2,
    maxLevel: null,
  },
  {
    code: "play_with_5_different_players",
    type: "social" as const,
    difficulty: "hard" as const,
    titleFr: "Ambassadeur",
    titleEn: "Ambassador",
    descriptionFr: "Joue avec 5 joueurs différents cette semaine",
    descriptionEn: "Play with 5 different players this week",
    targetValue: 5,
    acesReward: 300,
    minLevel: 4,
    maxLevel: null,
  },
  // Revanche / rejouer avec le même joueur
  {
    code: "rematch",
    type: "social" as const,
    difficulty: "easy" as const,
    titleFr: "Revanche !",
    titleEn: "Rematch!",
    descriptionFr: "Rejoue contre un adversaire de la semaine dernière",
    descriptionEn: "Play again against an opponent from last week",
    targetValue: 1,
    acesReward: 100,
    minLevel: 2,
    maxLevel: null,
  },
  {
    code: "rivalry",
    type: "social" as const,
    difficulty: "medium" as const,
    titleFr: "Rivalité",
    titleEn: "Rivalry",
    descriptionFr: "Joue 3 matchs contre le même adversaire cette semaine",
    descriptionEn: "Play 3 matches against the same opponent this week",
    targetValue: 3,
    acesReward: 175,
    minLevel: 3,
    maxLevel: null,
  },
  // Jouer contre des niveaux différents
  {
    code: "play_higher_level",
    type: "social" as const,
    difficulty: "easy" as const,
    titleFr: "David vs Goliath",
    titleEn: "David vs Goliath",
    descriptionFr: "Joue contre un joueur de niveau supérieur au tien",
    descriptionEn: "Play against a player with a higher level than yours",
    targetValue: 1,
    acesReward: 100,
    minLevel: 1,
    maxLevel: null,
  },
  {
    code: "mentor_match",
    type: "social" as const,
    difficulty: "easy" as const,
    titleFr: "Le mentor",
    titleEn: "The Mentor",
    descriptionFr: "Joue contre un joueur de niveau inférieur au tien",
    descriptionEn: "Play against a player with a lower level than yours",
    targetValue: 1,
    acesReward: 75,
    minLevel: 5,
    maxLevel: null,
  },
  // Inviter / jouer avec des nouveaux
  {
    code: "welcome_newcomer",
    type: "social" as const,
    difficulty: "medium" as const,
    titleFr: "Comité d'accueil",
    titleEn: "Welcome Committee",
    descriptionFr: "Joue avec un joueur qui a rejoint AceClub ce mois-ci",
    descriptionEn: "Play with a player who joined AceClub this month",
    targetValue: 1,
    acesReward: 150,
    minLevel: 3,
    maxLevel: null,
  },
  {
    code: "play_with_ghost",
    type: "social" as const,
    difficulty: "easy" as const,
    titleFr: "Chasseur de fantômes",
    titleEn: "Ghost Hunter",
    descriptionFr: "Joue contre un Ghost (joueur externe)",
    descriptionEn: "Play against a Ghost (external player)",
    targetValue: 1,
    acesReward: 75,
    minLevel: 1,
    maxLevel: null,
  },

  // ============================================
  // PERFORMANCE - Victoires et scores
  // ============================================
  {
    code: "win_1_match",
    type: "performance" as const,
    difficulty: "easy" as const,
    titleFr: "Première victoire",
    titleEn: "First Victory",
    descriptionFr: "Gagne 1 match cette semaine",
    descriptionEn: "Win 1 match this week",
    targetValue: 1,
    acesReward: 75,
    minLevel: 1,
    maxLevel: null,
  },
  {
    code: "win_3_matches",
    type: "performance" as const,
    difficulty: "medium" as const,
    titleFr: "Sur une lancée",
    titleEn: "On a Roll",
    descriptionFr: "Gagne 3 matchs cette semaine",
    descriptionEn: "Win 3 matches this week",
    targetValue: 3,
    acesReward: 175,
    minLevel: 3,
    maxLevel: null,
  },
  {
    code: "win_5_matches",
    type: "performance" as const,
    difficulty: "hard" as const,
    titleFr: "Inarrêtable",
    titleEn: "Unstoppable",
    descriptionFr: "Gagne 5 matchs cette semaine",
    descriptionEn: "Win 5 matches this week",
    targetValue: 5,
    acesReward: 400,
    minLevel: 5,
    maxLevel: null,
  },
  // Séries de victoires consécutives
  {
    code: "win_2_consecutive",
    type: "performance" as const,
    difficulty: "medium" as const,
    titleFr: "Série gagnante",
    titleEn: "Winning Streak",
    descriptionFr: "Gagne 2 matchs consécutifs",
    descriptionEn: "Win 2 consecutive matches",
    targetValue: 2,
    acesReward: 150,
    minLevel: 2,
    maxLevel: null,
  },
  {
    code: "win_3_consecutive",
    type: "performance" as const,
    difficulty: "hard" as const,
    titleFr: "Invincible",
    titleEn: "Invincible",
    descriptionFr: "Gagne 3 matchs consécutifs",
    descriptionEn: "Win 3 consecutive matches",
    targetValue: 3,
    acesReward: 350,
    minLevel: 4,
    maxLevel: null,
  },
  {
    code: "win_5_consecutive",
    type: "performance" as const,
    difficulty: "hard" as const,
    titleFr: "Légende",
    titleEn: "Legend",
    descriptionFr: "Gagne 5 matchs consécutifs",
    descriptionEn: "Win 5 consecutive matches",
    targetValue: 5,
    acesReward: 600,
    minLevel: 10,
    maxLevel: null,
  },
  // Victoires serrées / comeback
  {
    code: "close_victory",
    type: "performance" as const,
    difficulty: "medium" as const,
    titleFr: "Arrachée",
    titleEn: "Clutch",
    descriptionFr: "Gagne un match avec 2 points d'écart ou moins",
    descriptionEn: "Win a match with 2 points difference or less",
    targetValue: 1,
    acesReward: 150,
    minLevel: 2,
    maxLevel: null,
  },
  {
    code: "comeback_king",
    type: "performance" as const,
    difficulty: "hard" as const,
    titleFr: "Roi du comeback",
    titleEn: "Comeback King",
    descriptionFr: "Gagne un match après avoir été mené de 3 points ou plus",
    descriptionEn: "Win a match after being down by 3 or more points",
    targetValue: 1,
    acesReward: 300,
    minLevel: 5,
    maxLevel: null,
  },
  // Domination
  {
    code: "flawless_victory",
    type: "performance" as const,
    difficulty: "hard" as const,
    titleFr: "Victoire parfaite",
    titleEn: "Flawless Victory",
    descriptionFr: "Gagne un match 6-0",
    descriptionEn: "Win a match 6-0",
    targetValue: 1,
    acesReward: 250,
    minLevel: 3,
    maxLevel: null,
  },
  {
    code: "domination",
    type: "performance" as const,
    difficulty: "medium" as const,
    titleFr: "Domination",
    titleEn: "Domination",
    descriptionFr: "Gagne un match en ne concédant que 2 points ou moins",
    descriptionEn: "Win a match conceding only 2 points or less",
    targetValue: 1,
    acesReward: 175,
    minLevel: 3,
    maxLevel: null,
  },
  // Score total
  {
    code: "score_50_points",
    type: "performance" as const,
    difficulty: "medium" as const,
    titleFr: "Demi-centenaire",
    titleEn: "Half Century",
    descriptionFr: "Marque un total de 50 points cette semaine",
    descriptionEn: "Score a total of 50 points this week",
    targetValue: 50,
    acesReward: 175,
    minLevel: 3,
    maxLevel: null,
  },
  {
    code: "score_100_points",
    type: "performance" as const,
    difficulty: "hard" as const,
    titleFr: "Centurion",
    titleEn: "Centurion",
    descriptionFr: "Marque un total de 100 points cette semaine",
    descriptionEn: "Score a total of 100 points this week",
    targetValue: 100,
    acesReward: 350,
    minLevel: 5,
    maxLevel: null,
  },
  // Battre un joueur mieux classé
  {
    code: "giant_slayer",
    type: "performance" as const,
    difficulty: "medium" as const,
    titleFr: "Tueur de géants",
    titleEn: "Giant Slayer",
    descriptionFr: "Bats un joueur avec au moins 5 niveaux de plus que toi",
    descriptionEn: "Beat a player with at least 5 levels more than you",
    targetValue: 1,
    acesReward: 250,
    minLevel: 1,
    maxLevel: 20,
  },
  {
    code: "upset_master",
    type: "performance" as const,
    difficulty: "hard" as const,
    titleFr: "Maître de l'exploit",
    titleEn: "Upset Master",
    descriptionFr: "Bats 2 joueurs de niveau supérieur au tien cette semaine",
    descriptionEn: "Beat 2 players with a higher level than you this week",
    targetValue: 2,
    acesReward: 300,
    minLevel: 1,
    maxLevel: null,
  },
  // Équilibre / ratio
  {
    code: "balanced_week",
    type: "performance" as const,
    difficulty: "easy" as const,
    titleFr: "Équilibre",
    titleEn: "Balance",
    descriptionFr:
      "Termine la semaine avec au moins autant de victoires que de défaites (min 4 matchs)",
    descriptionEn: "End the week with at least as many wins as losses (min 4 matches)",
    targetValue: 4,
    acesReward: 125,
    minLevel: 2,
    maxLevel: null,
  },
  {
    code: "winning_week",
    type: "performance" as const,
    difficulty: "medium" as const,
    titleFr: "Semaine victorieuse",
    titleEn: "Winning Week",
    descriptionFr: "Termine la semaine avec plus de victoires que de défaites (min 5 matchs)",
    descriptionEn: "End the week with more wins than losses (min 5 matches)",
    targetValue: 5,
    acesReward: 200,
    minLevel: 3,
    maxLevel: null,
  },
  // Amélioration personnelle
  {
    code: "beat_personal_best",
    type: "performance" as const,
    difficulty: "medium" as const,
    titleFr: "Record personnel",
    titleEn: "Personal Best",
    descriptionFr: "Joue plus de matchs cette semaine que la semaine dernière",
    descriptionEn: "Play more matches this week than last week",
    targetValue: 1,
    acesReward: 150,
    minLevel: 2,
    maxLevel: null,
  },
  {
    code: "improvement",
    type: "performance" as const,
    difficulty: "medium" as const,
    titleFr: "Progression",
    titleEn: "Improvement",
    descriptionFr: "Gagne plus de matchs cette semaine que la semaine dernière",
    descriptionEn: "Win more matches this week than last week",
    targetValue: 1,
    acesReward: 175,
    minLevel: 3,
    maxLevel: null,
  },
];

async function main() {
  console.log("Seeding challenge templates...\n");

  for (const template of CHALLENGE_TEMPLATES) {
    try {
      await db
        .insert(challengeTemplate)
        .values({
          ...template,
          isActive: true,
        })
        .onConflictDoNothing();
      console.log(`Inserted: ${template.code}`);
    } catch (error) {
      console.error(`Failed to insert ${template.code}:`, error);
    }
  }

  console.log("\nDone!");
  process.exit(0);
}

main();
